version: '3'

services:
  minio1:
    image: minio/minio:RELEASE.2021-11-24T23-19-33Z
    command: server --console-address ":9001" data/disk1
    labels:
      traefik.http.services.minio.loadbalancer.server.port: 9000
      traefik.http.routers.minio.rule: 'PathPrefix(`/`)'
      traefik.http.routers.minio.tls: 'false'
      traefik.http.routers.minio.tls.certresolver: 'default'
      traefik.enable: 'true'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominiominio
  traefik:
    image: ghcr.io/eugenmayer/traefik:2.x
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 200000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TRAEFIK_ACME_ENABLE: 'false'
      TRAEFIK_HTTPS_ENABLE: 'false'
      TRAEFIK_ACME_CHALLENGE: 'http'
      TRAEFIK_DOCKER_ENABLE: 'true'
      TRAEFIK_DOCKER_EXPOSEDBYDEFAULT: 'false'
      TRAEFIK_ADMIN_ENABLE: 'true'
      TRAEFIK_ADMIN_SSL: 'false'

  nginx:
    image: bitnami/nginx
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 200000
    volumes:
      - ./nginx/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf

  envoy:
    image: envoyproxy/envoy:v1.20-latest
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml

  haproxy:
    image: haproxy:2.1.2
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 200000
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  warp:
    image: minio/warp:v0.5.5
    entrypoint:
      - sleep
      - '80000'
